# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(241, 383)
        self.centralWidget = QtWidgets.QWidget(Calculator)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel { qproperty-alignment: \'AlignVCenter | AlignRight\'; border: 1px solid gray; } background-color : white;")
        self.label.setObjectName("label")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(0, 60, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet(" QPushButton { background-color: rgb(215, 215, 215); border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #BEBEBE, stop: 1 #D7D7D7); }")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_plusMinus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_plusMinus.setGeometry(QtCore.QRect(60, 60, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_plusMinus.setFont(font)
        self.pushButton_plusMinus.setStyleSheet(" QPushButton { background-color: rgb(215, 215, 215); border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #BEBEBE, stop: 1 #D7D7D7); }")
        self.pushButton_plusMinus.setObjectName("pushButton_plusMinus")
        self.pushButton_percent = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_percent.setGeometry(QtCore.QRect(120, 60, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_percent.setFont(font)
        self.pushButton_percent.setStyleSheet(" QPushButton { background-color: rgb(215, 215, 215); border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #BEBEBE, stop: 1 #D7D7D7); }")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.pushButton_divide = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_divide.setGeometry(QtCore.QRect(180, 60, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setStyleSheet("QPushButton { background-color: rgb(255, 151, 57); color: white; border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FF7832, stop: 1 #FF9739); }")
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_multiply = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_multiply.setGeometry(QtCore.QRect(180, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("QPushButton { background-color: rgb(255, 151, 57); color: white; border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FF7832, stop: 1 #FF9739); }")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_subtract = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_subtract.setGeometry(QtCore.QRect(180, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_subtract.setFont(font)
        self.pushButton_subtract.setStyleSheet("QPushButton { background-color: rgb(255, 151, 57); color: white; border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FF7832, stop: 1 #FF9739); }")
        self.pushButton_subtract.setObjectName("pushButton_subtract")
        self.pushButton_add = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_add.setGeometry(QtCore.QRect(180, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("QPushButton { background-color: rgb(255, 151, 57); color: white; border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FF7832, stop: 1 #FF9739); }")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_equals = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_equals.setGeometry(QtCore.QRect(180, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_equals.setFont(font)
        self.pushButton_equals.setStyleSheet("QPushButton { background-color: rgb(255, 151, 57); color: white; border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FF7832, stop: 1 #FF9739); }")
        self.pushButton_equals.setObjectName("pushButton_equals")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 300, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("QPushButton { border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa); }")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_decimal = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_decimal.setEnabled(True)
        self.pushButton_decimal.setGeometry(QtCore.QRect(120, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_decimal.setFont(font)
        self.pushButton_decimal.setStyleSheet(" QPushButton { background-color: rgb(215, 215, 215); border: 1px solid gray; } QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #BEBEBE, stop: 1 #D7D7D7); }")
        self.pushButton_decimal.setObjectName("pushButton_decimal")
        Calculator.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Calculator)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 241, 22))
        self.menuBar.setStyleSheet("QMenuBar:hover {background-color: rgb(255, 132, 6);}")
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setStyleSheet("QMenu:hover {background-color: rgb(255, 132, 6);}")
        self.menuSettings.setObjectName("menuSettings")
        self.menuColor_Scheme = QtWidgets.QMenu(self.menuSettings)
        self.menuColor_Scheme.setObjectName("menuColor_Scheme")
        self.menuLanguage = QtWidgets.QMenu(self.menuSettings)
        self.menuLanguage.setObjectName("menuLanguage")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        Calculator.setMenuBar(self.menuBar)
        self.actionMinimal_Bright_Orange = QtWidgets.QAction(Calculator)
        self.actionMinimal_Bright_Orange.setCheckable(False)
        self.actionMinimal_Bright_Orange.setChecked(False)
        self.actionMinimal_Bright_Orange.setEnabled(True)
        self.actionMinimal_Bright_Orange.setObjectName("actionMinimal_Bright_Orange")
        self.actionFeather_Light_Blue = QtWidgets.QAction(Calculator)
        self.actionFeather_Light_Blue.setCheckable(False)
        self.actionFeather_Light_Blue.setEnabled(True)
        self.actionFeather_Light_Blue.setObjectName("actionFeather_Light_Blue")
        self.actionSelect_Font = QtWidgets.QAction(Calculator)
        self.actionSelect_Font.setObjectName("actionSelect_Font")
        self.actionQuit = QtWidgets.QAction(Calculator)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHelp = QtWidgets.QAction(Calculator)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(Calculator)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCheck_for_updates = QtWidgets.QAction(Calculator)
        self.actionCheck_for_updates.setObjectName("actionCheck_for_updates")
        self.actionEnglish = QtWidgets.QAction(Calculator)
        self.actionEnglish.setObjectName("actionEnglish")
        self.menuColor_Scheme.addAction(self.actionMinimal_Bright_Orange)
        self.menuColor_Scheme.addAction(self.actionFeather_Light_Blue)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuSettings.addAction(self.menuColor_Scheme.menuAction())
        self.menuSettings.addAction(self.actionSelect_Font)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.menuLanguage.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionCheck_for_updates)
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.label.setText(_translate("Calculator", "0"))
        self.pushButton_clear.setText(_translate("Calculator", "C"))
        self.pushButton_plusMinus.setText(_translate("Calculator", "±"))
        self.pushButton_percent.setText(_translate("Calculator", "%"))
        self.pushButton_divide.setText(_translate("Calculator", "÷"))
        self.pushButton_multiply.setText(_translate("Calculator", "x"))
        self.pushButton_9.setText(_translate("Calculator", "9"))
        self.pushButton_7.setText(_translate("Calculator", "7"))
        self.pushButton_8.setText(_translate("Calculator", "8"))
        self.pushButton_subtract.setText(_translate("Calculator", "-"))
        self.pushButton_add.setText(_translate("Calculator", "+"))
        self.pushButton_2.setText(_translate("Calculator", "2"))
        self.pushButton_6.setText(_translate("Calculator", "6"))
        self.pushButton_1.setText(_translate("Calculator", "1"))
        self.pushButton_4.setText(_translate("Calculator", "4"))
        self.pushButton_3.setText(_translate("Calculator", "3"))
        self.pushButton_5.setText(_translate("Calculator", "5"))
        self.pushButton_equals.setText(_translate("Calculator", "="))
        self.pushButton_0.setText(_translate("Calculator", "0"))
        self.pushButton_decimal.setText(_translate("Calculator", "."))
        self.menuSettings.setTitle(_translate("Calculator", "Settings"))
        self.menuColor_Scheme.setStatusTip(_translate("Calculator", "Choose a color scheme"))
        self.menuColor_Scheme.setTitle(_translate("Calculator", "Color Scheme"))
        self.menuLanguage.setStatusTip(_translate("Calculator", "Choose a language :)"))
        self.menuLanguage.setTitle(_translate("Calculator", "Language"))
        self.menuHelp.setTitle(_translate("Calculator", "Help"))
        self.actionMinimal_Bright_Orange.setText(_translate("Calculator", "Bright Orange White"))
        self.actionMinimal_Bright_Orange.setStatusTip(_translate("Calculator", "Use Bright Orange White color sheme"))
        self.actionFeather_Light_Blue.setText(_translate("Calculator", "Feather Light Blue"))
        self.actionFeather_Light_Blue.setStatusTip(_translate("Calculator", "Use Feather Light Blue color sheme"))
        self.actionSelect_Font.setText(_translate("Calculator", "Select Font..."))
        self.actionSelect_Font.setStatusTip(_translate("Calculator", "Select font family and font size"))
        self.actionQuit.setText(_translate("Calculator", "Quit"))
        self.actionQuit.setStatusTip(_translate("Calculator", "Quit Application"))
        self.actionQuit.setShortcut(_translate("Calculator", "Ctrl+Q"))
        self.actionHelp.setText(_translate("Calculator", "Help"))
        self.actionHelp.setStatusTip(_translate("Calculator", "Help"))
        self.actionAbout.setText(_translate("Calculator", "About"))
        self.actionAbout.setStatusTip(_translate("Calculator", "About Calculator"))
        self.actionCheck_for_updates.setText(_translate("Calculator", "Check for updates"))
        self.actionCheck_for_updates.setStatusTip(_translate("Calculator", "Check for updates"))
        self.actionEnglish.setText(_translate("Calculator", "English"))
        self.actionEnglish.setStatusTip(_translate("Calculator", "lol"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())

